### ISSUE TITLE
Version number is not updated

### ISSUE THREAD

**Issue by Randolf-SPEYK** [Tools4everBV/HelloID-Conn-Prov-Source-Visma.net-HRM-API#17]
Version 3 of this connector is published in February. In August it was updated but the version number in the scripts and on Github is still 3.0.0. That needs to be updated.

**Comment by rvddijssel** [comment]
In August we introduced release packages of the github repo because of the import source from GitHub functionality. This was done with the same version as shown in the Readme because there was no change in the connector. Only release package, readme and icon was changed. Therefore no new version is needed

**Comment by Randolf-SPEYK** [comment]
But how do you explain the difference in scripts you receive with the import button and the scripts available on Github. They are different but with the same version. That is strange in my opinion.

**Comment by rvddijssel** [comment]
Sorry, I misunderstood the issue. I've created a new version for the changes. Also, I checked why this happend but the fix was commited on the day that we introduced the releases therefore we missed the release. So it should not happen with other connectors because it's the procedure to create a new release when a pull request is approved and merged.
